site_name: Documentation
nav:
    - Introduction: index.md

    - Overview: 
        - ONEm Platform: micro_app_platform.md
        - Micro-apps: micro_apps_basics.md
        - Multi-channel: multi_channel_basics.md       
    - Quick Start: 
        - Node.js: quick_start_nodejs.md
        - Python: quick_start_python.md
    - Step by Step:
        - Node.js: getting_started_node_js.md
        - Python: step_by_step_python.md
    - Reference:
        - Menus: menus.md
        - Forms: forms.md
    
    # - Core concepts:
    #     - Structure: core/structure.md
    #     - Headers and footers: core/headers_footers.md
    #     - Menus and forms: core/menus_forms.md
    #     - Paging: core/paging.md
    #     - Your micro-app: core/your_micro_app.md
    #     - Accessing your micro-app: core/accessing_your_micro_app.md
    #     - Reserved verbs: core/reserved_verbs.md
    #     - Framework capabilities: 
    #         - (callback vs ONEm API): core/callback_api.md
    #         - Validation: core/todo.md

    # - Getting started:
    #       - At a glance: getting_started/glance.md
    #       - Run in 60 seconds: getting_started/run_remote_60s.md
    #       - Python:
    #           - Pre-requisites: getting_started/python_prereq.md
    #           - Run locally: getting_started/python_run_local.md
    #       - Node.js:
    #           - Pre-requisites: getting_started/nodejs_prereq.md
    #           - Run locally: getting_started/nodejs_run_local.md
    # - Building:
    #     - Structure:
    #         - Response: building/response.md
    #         - Menu: building/menu.md
    #         - Form: building/form.md
    #         - Raw: building/raw.md
    #     - SDK:
    #         - SDK Essentials: building/essentials.md
    #         - HTML tags: building/html.md
    #         - HTML to Response: building/html_to_response.md
    #         - How to use the SDKs: building/how_to_use_sdk.md
    # - Guides:
    #     - Building a post board micro-app:
    #         - Basics: use_case/post_demo_app_intro.md
    #         - Micro app landing: use_case/postv1.md
    #         - Search through posts: use_case/postv2.md
    #         - Using the ONEm API: use_case/postv3.md
    #     - Building a skillhire micro-app using templates: todo.md
    # - References:
    #     - ONEm API: https://app.swaggerhub.com/apis-docs/romeo1m/schemajson/v1.0#/
    #     - ONEM SDK: https://www.npmjs.com/package/onemsdk/
    # - Reference:
    #     - ONEm API: !!python/object/apply:os.getenv ['RESTDAPI_REDOC']
    #     - ONEm SDK: !!python/object/apply:os.getenv ['ONEMSDK_DOCS']

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - javascript
        - python
        - html
        - bash
        - pug
        - ejs
        - json
    # custom_dir: theme/material/
    favicon: assets/favicon.ico
    language: en
    palette:
        primary: white
        accent: blue
    logo: assets/onem-logo.svg
plugins:
    - search
    - markdownextradata #https://github.com/rosscdh/mkdocs-markdownextradata-plugin
extra:
  links:
    portal: !!python/object/apply:os.getenv ['DEV_PORTAL_SITE']
    onem_api_docs: !!python/object/apply:os.getenv ['RESTDAPI_DOCS']
    schema_url: !!python/object/apply:os.getenv ['SWAGGER_SCHEMA_URL']
    nodejs_sdk_repo: !!python/object/apply:os.getenv ['NODEJS_SDK_REPO']
    python_sdk_repo: !!python/object/apply:os.getenv ['PYTHON_SDK_REPO']
    todo_app:
      github_nodejs_url: !!python/object/apply:os.getenv ['TODO_APP_GITHUB_NODEJS_URL']
  todo_app:
    github_py_url: !!python/object/apply:os.getenv ['TODO_APP_GITHUB_PY_URL']
  post_app:
    github_py_url: !!python/object/apply:os.getenv ['POST_APP_GITHUB_PY_URL']

extra_css:
    - 'assets/stylesheets/styles.css'
extra_javascript:
    - 'assets/js/jquery-3.4.1.min.js'
    #- 'assets/js/opensidenav.js'
markdown_extensions:
    - pymdownx.superfences
    - admonition
    - toc:
        permalink: true
    - codehilite:
        linenums: true
    - markdown_include.include:
        base_path: docs
