site_name: Documentation
nav:
    - Introduction: index.md

    - What is it?:
        - Micro app basics: micro_apps_basics.md
        - How it works: how_it_works.md

    - Core concepts:
        - Structure: core/structure.md
        - Headers and footers: core/headers_footers.md
        - Menus and forms: core/menus_forms.md
        - Paging: core/paging.md
        - Verbs: core/verbs.md
        - Framework capabilities: 
            - (callback vs RestDAPI): core/todo.md
            - Validation: core/todo.md
        - Your micro-app: core/your_micro_app.md

    - Getting started:
          - At a glance: getting_started/glance.md
          - Python:
              - Pre-requisites: getting_started/python_prereq.md
              - Run locally: getting_started/python_run_local.md
              - Run remotely: getting_started/python_run_remote.md
          - Node.js:
              - Pre-requisites: getting_started/nodejs_prereq.md
              - Run locally: getting_started/nodejs_run_local.md
              - Run remotely: getting_started/nodejs_run_remote.md
    - Building:
        - How to register your app: building/register.md
        - Structure:
            - Menus: building/menus.md
            - Forms: building/forms.md
            - Raw: building/raw.md
        - SDK:
            - HTML: building/html.md

    - API:
        - Purpose: api/purpose.md
        - Documentation: !!python/object/apply:os.getenv ['RESTDAPI_REDOC']

    - Use Case:
        - Introduction: use_case/post_demo_app_intro.md
        - post v1: use_case/postv1.md
        - post v2: use_case/postv2.md
        - post v3: use_case/postv3.md

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - javascript
        - python
        - html
    # custom_dir: theme/material/
    favicon: assets/favicon.ico
    language: en
    palette:
        primary: white
        accent: blue
    # feature:
    #     tabs: true
    logo: assets/onem-logo.svg
plugins:
    - search
    - markdownextradata #https://github.com/rosscdh/mkdocs-markdownextradata-plugin
extra:
  links:
    portal: !!python/object/apply:os.getenv ['DEV_PORTAL_SITE']
    api: !!python/object/apply:os.getenv ['RESTDAPI_DOCS']
  todo_app:
    github_py_url: !!python/object/apply:os.getenv ['TODO_APP_GITHUB_PY_URL']

extra_css:
    - 'assets/stylesheets/styles.css'
extra_javascript:
    - 'assets/js/opensidenav.js'
markdown_extensions:
    - codehilite
    - markdown_include.include:
        base_path: docs
