site_name: Documentation
nav:
    - Home: index.md
    - Developer Portal: http://testtool.dhq.onem:6060/
    - API Reference: http://172.16.38.113:6212/redoc
    - Getting Started:
        - NodeJS: getting-started/getting-started-nodejs.md
        - Python: getting-started/getting-started-python.md
theme:
    name: material
    # custom_dir: theme/material/
    favicon: assets/favicon.ico
    language: en
    palette:
        primary: white
        accent: blue
    # feature:
    #     tabs: true
    logo: assets/onem-logo.svg
extra_css:
  - 'stylesheets/styles.css'




