site_name: Documentation
nav:
    - Introduction: index.md

    - What is it?:
        - Micro app basics: micro_apps_basics.md
        - How it works: how_it_works.md

    - Core concepts:
        - Structure: core/structure.md
        - Headers and footers: core/headers_footers.md
        - Menus and forms: core/menus_forms.md
        - Paging: core/paging.md
        - Your micro-app: core/your_micro_app.md
        - Accessing your micro-app: core/accessing_your_micro_app.md
        - Reserved verbs: core/reserved_verbs.md
        - Framework capabilities: 
            - (callback vs RestDAPI): core/callback_api.md
            - Validation: core/todo.md

    - Getting started:
          - At a glance: getting_started/glance.md
          - Run in 60 seconds: getting_started/run_remote_60s.md
          - Python:
              - Pre-requisites: getting_started/python_prereq.md
              - Run locally: getting_started/python_run_local.md
          - Node.js:
              - Pre-requisites: getting_started/nodejs_prereq.md
              - Run locally: getting_started/nodejs_run_local.md
    - Building:
        - Structure:
            - Response: building/response.md
            - Menu: building/menu.md
            - Form: building/form.md
            - Raw: building/raw.md
        - SDK:
            - About: building/about_sdk.md
            - HTML tags: building/html.md
            - HTML to Response: building/html_to_response.md
            - How to use the SDKs: building/how_to_use_sdk.md

    - Use Case:
        - Introduction: use_case/post_demo_app_intro.md
        - post v1: use_case/postv1.md
        - post v2: use_case/postv2.md
        - post v3: use_case/postv3.md

    - API:
        - Purpose: api/purpose.md
        - Documentation: !!python/object/apply:os.getenv ['RESTDAPI_REDOC']

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - javascript
        - python
        - html
        - bash
    # custom_dir: theme/material/
    favicon: assets/favicon.ico
    language: en
    palette:
        primary: white
        accent: blue
    # feature:
    #     tabs: true
    logo: assets/onem-logo.svg
plugins:
    - search
    - markdownextradata #https://github.com/rosscdh/mkdocs-markdownextradata-plugin
extra:
  links:
    portal: !!python/object/apply:os.getenv ['DEV_PORTAL_SITE']
    api: !!python/object/apply:os.getenv ['RESTDAPI_DOCS']
    schema_url: !!python/object/apply:os.getenv ['SWAGGER_SCHEMA_URL']
  todo_app:
    github_py_url: !!python/object/apply:os.getenv ['TODO_APP_GITHUB_PY_URL']

extra_css:
    - 'assets/stylesheets/styles.css'
extra_javascript:
    - 'assets/js/jquery-3.4.1.min.js'
    - 'assets/js/opensidenav.js'
markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - codehilite:
        linenums: true
    - markdown_include.include:
        base_path: docs
